
# Indentation Preferences
indent_type = "Spaces"     # Clean, consistent indentation
indent_width = 2           # Compact yet readable 2-space indents

# Line Length Management
column_width = 120         # Generous width for readable code
# Allows for comfortable viewing without excessive line wrapping

# Optional: Additional Styling Configurations
line_endings = "Unix"      # Consistent line endings
quote_style = "AutoPreferSingle"  # Prefer single quotes when possible

# Experimental Features (Uncomment if desired)
# call_parentheses = "Always"  # Explicit function call parentheses
# collapse_simple_statement = "Never"  # Preserve statement formatting
